const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../src/core.js');const D=JSON.parse(fs.readFileSync(path.join(__dirname,'../docs/content-registry.json'),'utf8'));
let total=0;const outcomes=[];function test(name,fn){try{fn();outcomes.push({name,passed:true});total++;}catch(e){outcomes.push({name,passed:false,error:e.message});throw e;}}
const make=(ids=['b22-1a'],kind='training')=>C.assign(C.initial(),D,{id:'a',title:'اختبار',questionIds:ids,studentIds:['demo-1'],kind});
const send=(s,value,id='r1',questionId='b22-1a',extra={})=>C.submit(s,D,{id,studentId:'demo-1',assignmentId:'a',questionId,value,...extra});
test('Source catalog has 6 units and 29 ordered components',()=>{assert.equal(D.units.length,6);assert.equal(D.units.flatMap(u=>u.lessons).length,29);});
test('Only Al-Mustaqbal is marked content-ready',()=>assert.deepEqual(D.units.flatMap(u=>u.lessons).filter(l=>l.ready).map(l=>l.id),['u1-l1']));
test('All IDs are unique',()=>{const ids=D.questions.concat(D.stories.flatMap(s=>s.questions)).map(q=>q.id);assert.equal(ids.length,new Set(ids).size);});
test('Book and authored tasks counted separately',()=>{assert.equal(D.questions.filter(q=>q.origin==='book').length,24);assert.equal(D.questions.filter(q=>q.origin==='parallel').length,3);assert.equal(D.questions.filter(q=>q.origin==='independent').length,3);});
test('All objective answer indexes are valid',()=>D.questions.concat(D.stories.flatMap(s=>s.questions)).filter(q=>q.type==='mcq').forEach(q=>assert.ok(Number.isInteger(q.answer)&&q.answer>=0&&q.answer<q.choices.length)));
test('Fresh workspace has no fabricated scores',()=>{const s=C.summary(C.initial(),D,'demo-1');assert.equal(s.percent,null);assert.equal(s.count,0);assert.equal(s.points,0);});
test('Assignments reject nonexistent learners',()=>assert.throws(()=>C.assign(C.initial(),D,{id:'a',questionIds:['b22-1a'],studentIds:['bad']})));
test('Assignments reject empty selections',()=>assert.throws(()=>C.assign(C.initial(),D,{id:'a',questionIds:[],studentIds:['demo-1']})));
test('Flagged reference question cannot be assigned',()=>assert.throws(()=>make(['b21-1b'])));
test('Oral observation is not disguised as a quiz',()=>assert.throws(()=>make(['b24-1'])));
test('Independent mode requires distinct authored questions',()=>assert.throws(()=>make(['b22-1a'],'independent')));
test('Correct answer receives 2 marks and 10 points',()=>{const s=send(make(),1);assert.equal(s.responses[0].score,2);assert.equal(C.points(s,'demo-1'),10);});
test('Wrong answer is not marked excellent',()=>{const s=send(make(),0);assert.equal(s.responses[0].score,0);assert.equal(s.responses[0].status,'retry');assert.equal(C.points(s,'demo-1'),0);});
test('No answer cannot be submitted',()=>assert.throws(()=>send(make(),null)));
test('Out of range answer is rejected',()=>assert.throws(()=>send(make(),9)));
test('Duplicate submission ID is idempotent',()=>{const s=send(make(),1);assert.deepEqual(send(s,1),s);});
test('New click after correct answer does not farm points',()=>{const s=send(make(),1);assert.deepEqual(send(s,1,'r2'),s);});
test('Retry awards once with reduced points',()=>{const s=send(send(make(),0),1,'r2');assert.equal(C.points(s,'demo-1'),5);assert.equal(s.responses.length,2);});
test('Hinted first answer awards only 5 points',()=>assert.equal(C.points(send(make(),1,'r1','b22-1a',{usedHint:true}),'demo-1'),5));
test('At most three training attempts',()=>{let s=make();for(let i=0;i<5;i++)s=send(s,0,'r'+i);assert.equal(s.responses.length,3);});
test('Question rewards do not repeat in another assignment',()=>{let s=send(make(),1);s=C.assign(s,D,{id:'b',title:'جديدة',questionIds:['b22-1a'],studentIds:['demo-1']});s=C.submit(s,D,{id:'rb',studentId:'demo-1',assignmentId:'b',questionId:'b22-1a',value:1});assert.equal(C.points(s,'demo-1'),10);});
test('A different learner cannot answer an unassigned task',()=>assert.throws(()=>C.submit(make(),D,{id:'r',studentId:'demo-2',assignmentId:'a',questionId:'b22-1a',value:1})));
test('Open answers are pending, not incorrect',()=>{const s=send(make(['b20-1']),'لأن الماء قليل.','r','b20-1');assert.equal(s.responses[0].score,null);assert.equal(s.responses[0].status,'pending');assert.equal(C.summary(s,D,'demo-1').percent,null);});
test('Blank open answer is rejected',()=>assert.throws(()=>send(make(['b20-1']),'   ','r','b20-1')));
test('Unknown Arabic synonym is queued for review',()=>{const s=send(make(['b21-2-رحل']),'غادر','r','b21-2-رحل');assert.equal(s.responses[0].status,'pending');});
test('Known Arabic synonym ignores optional diacritics',()=>{const s=send(make(['b21-2-رحل']),'ذَهَبَ','r','b21-2-رحل');assert.equal(s.responses[0].score,2);});
test('Teacher review awards points only once',()=>{let s=send(make(['b20-1']),'لأن الماء قليل.','r','b20-1');s=C.review(s,'r',2,'معنى صحيح.');const again=C.review(s,'r',2,'مرة ثانية');assert.equal(C.points(again,'demo-1'),10);assert.deepEqual(again,s);});
test('Invalid review score is rejected',()=>{let s=send(make(['b20-1']),'الماء قليل','r','b20-1');assert.throws(()=>C.review(s,'r',3));});
test('Independent attempt cannot be repeated',()=>{let s=make(['i-infer-1'],'independent');s=send(s,0,'r1','i-infer-1');s=send(s,1,'r2','i-infer-1');assert.equal(s.responses.length,1);});
test('Independent hints are rejected',()=>assert.throws(()=>send(make(['i-infer-1'],'independent'),1,'r1','i-infer-1',{usedHint:true})));
test('Pending reports cannot be published',()=>{const s=send(make(['b20-1']),'الماء قليل','r','b20-1');assert.equal(Object.keys(C.publish(s,D).reports).length,0);});
test('Empty reports cannot be published',()=>assert.equal(Object.keys(C.publish(C.initial(),D).reports).length,0));
test('Publish is scoped to learners with reviewed data',()=>{const s=C.publish(send(make(),1),D);assert.deepEqual(Object.keys(s.reports),['demo-1']);});
test('Published snapshot is independent of later attempts',()=>{let s=C.publish(send(make(),1),D);const old=JSON.stringify(s.reports['demo-1']);s=C.assign(s,D,{id:'b',title:'تدريب جديد',questionIds:['b22-1b'],studentIds:['demo-1']});s=C.submit(s,D,{id:'r2',studentId:'demo-1',assignmentId:'b',questionId:'b22-1b',value:0});assert.equal(JSON.stringify(s.reports['demo-1']),old);});
test('No scores leak between fictional learners',()=>{const s=send(make(),1);assert.equal(C.summary(s,D,'demo-2').graded,0);});
test('Domain functions do not mutate input',()=>{const s=make(),before=JSON.stringify(s);send(s,1);assert.equal(JSON.stringify(s),before);});
test('Distinct story challenges are counted only after answering all',()=>{const st=D.stories[0];let s=C.assign(C.initial(),D,{id:'a',title:st.title,questionIds:st.questions.map(q=>q.id),studentIds:['demo-1'],kind:'story',storyId:st.id});assert.equal(C.summary(s,D,'demo-1').completedStories,0);st.questions.forEach((q,i)=>s=send(s,q.answer,'r'+i,q.id));assert.equal(C.summary(s,D,'demo-1').completedStories,1);});
fs.writeFileSync(path.join(__dirname,'../docs/domain-test-results.json'),JSON.stringify({passed:total,failed:0,tests:outcomes},null,2));console.log(`${total} domain tests passed`);
