(() => {
 'use strict';
 const D=window.ITQAN_DATA,C=window.ITQAN_CORE,KEY='itqan-v9-acceptance-1',app=document.getElementById('app'),modal=document.getElementById('modal');
 if(!D||!C){app.textContent='تعذر تحميل ملفات المنصة. تأكدي من رفع مجلد src مع index.html، ثم أعيدي تحميل الصفحة.';return;}
 const paths={home:'M3 10l9-7 9 7v10H3z M9 20v-7h6v7',book:'M3 4h5a5 5 0 0 1 4 2v15a5 5 0 0 0-4-2H3z M21 4h-5a5 5 0 0 0-4 2 M12 21a5 5 0 0 1 4-2h5V4',clock:'M12 8v5l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',play:'M8 5l11 7-11 7z',chart:'M4 20h17 M7 16v-5 M12 16V4 M17 16V8',users:'M15 21v-2a5 5 0 0 0-5-5H8a5 5 0 0 0-5 5v2 M13 6a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M17 3a4 4 0 0 1 0 8 M21 21v-2a5 5 0 0 0-3-4',check:'M4 12l5 5L20 6',arrow:'M18 12H5 M11 6l-6 6 6 6',star:'M12 2l3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',shield:'M12 2l9 4v6c0 5-9 10-9 10S3 17 3 12V6z M8 12l3 3 5-6',info:'M12 8v.1 M12 11v6 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',close:'M5 5l14 14 M19 5L5 19',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',print:'M6 9V3h12v6 M6 17H3V9h18v8h-3 M6 14h12v7H6z',send:'M21 3L9 15 M21 3l-5 18-5-8-8-5z',target:'M20 12a8 8 0 1 1-8-8 M16 12a4 4 0 1 1-4-4 M12 12l9-9 M16 3h5v5',seed:'M12 21v-8 M12 15C2 15 2 6 2 6s10-1 10 9 M12 12c0-9 10-10 10-10s1 10-10 10',window:'M4 3h16v18H4z M4 12h16 M12 3v18',refresh:'M20 7a9 9 0 1 0 1 8 M20 2v6h-6',fullscreen:'M4 9V4h5 M15 4h5v5 M20 15v5h-5 M9 20H4v-5',pause:'M8 4v16 M16 4v16',up:'M6 15l6-6 6 6',down:'M6 9l6 6 6-6',folder:'M3 5h7l2 3h9v12H3z',flag:'M5 21V3 M5 3c4-3 9 3 14 0v10c-5 3-10-3-14 0',link:'M9 15l6-6 M7 14l-2 2a4 4 0 0 0 6 6l3-3 M10 5l3-3a4 4 0 0 1 6 6l-3 3'};
 const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.book}"/></svg>`;
 const e=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const n=x=>new Intl.NumberFormat('ar-QA').format(x),uid=prefix=>prefix+'-'+(globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2));
 let storageWarning='',S=C.initial();
 try{const t=localStorage.getItem(KEY);if(t){const v=JSON.parse(t);if(v.schema===1&&Array.isArray(v.assignments)&&Array.isArray(v.responses)&&v.students?.length===3)S=v;else storageWarning='لم نعتمد البيانات المحلية غير المتوافقة. افتتحت مساحة تجربة جديدة.';}}catch{storageWarning='الحفظ الدائم غير متاح في هذا المتصفح. تبقى التجربة عاملة، ويمكن تنزيل نسخة من البيانات.';}
 const V={unit:'u1',tab:'book',query:'',skill:'all',selected:[...D.defaultTaskIds],learner:'demo-1',context:'class',font:17,quizId:null,qi:0,selection:null,retry:false,hinted:false,reportStudent:'demo-1',game:null,observation:{},time:0,running:false,timerAt:0,scope:'all',activeLesson:S.selectedLesson||'u1-l1',lastLesson:null,classIndex:0};
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(S));}catch{storageWarning='تعذر الحفظ الدائم على هذا الجهاز. نزّلي بيانات التجربة قبل إغلاق الصفحة.';}};
 const route=()=>{const a=(location.hash||'#teacher/home').slice(1).split('/');return {role:['teacher','student','family'].includes(a[0])?a[0]:'teacher',page:a[1]||'home',id:a.slice(2).join('/')};};
 const go=(path)=>{if(location.hash==='#'+path)render();else location.hash=path;};
 const notify=msg=>{const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),3600);};
 const act=(name,text,cls='btn',extras='')=>`<button type="button" class="${cls}" data-do="${name}" ${extras}>${text}</button>`;
 const pill=(text,cls='')=>`<span class="pill ${cls}">${text}</span>`;
 const link=(path,text,cls='btn secondary')=>`<a class="${cls}" href="#${path}">${text}</a>`;
 const qby=id=>C.question(D,id),student=()=>S.students.find(s=>s.id===V.learner),readiness=()=>S.students.map(st=>C.summary(S,D,st.id));

 const lessonBy=id=>D.units.flatMap(u=>u.lessons.map(l=>({...l,unitTitle:u.title,unitId:u.id}))).find(l=>l.id===id);
 const currentLesson=()=>lessonBy(route().page==='lesson'?route().id:V.activeLesson)||lessonBy('u1-l1');
 const lessonQs=(id,origin='book')=>D.questions.filter(q=>q.lesson===id&&q.origin===origin);
 const eligible=q=>q&&!q.needsContentReview&&q.type!=='observation'&&!q.activityOnly;
 const taskIds=(id,origin='book')=>lessonQs(id,origin).filter(eligible).slice(0,5).map(q=>q.id);
 const pageRange=l=>'<bdi dir="ltr">'+n(l.startPage)+(l.endPage!==l.startPage?'–'+n(l.endPage):'')+'</bdi>';
 const bookImage=p=>'assets/book/p'+String(p).padStart(3,'0')+'.webp';
 const answerImage=p=>'assets/answers/a'+String(p).padStart(2,'0')+'.webp';
 const text=s=>e(s).replace(/\n/g,'<br>');
 let currentSource=null;
 function chooseLessonMarkup(id=V.activeLesson){return `<div class="field lesson-selector"><label for="activeLesson">الدرس الذي تعملين عليه</label><select class="control" id="activeLesson">${D.units.map(u=>`<optgroup label="${e(u.title)}">${u.lessons.map(l=>`<option value="${l.id}" ${l.id===id?'selected':''}>${e(l.kind)}: ${e(l.title)}</option>`).join('')}</optgroup>`).join('')}</select></div>`;}
 function sourceButtons(q,teacher=true){return `<div class="row source-buttons">${q.page?act('source-page',icon('book')+' صفحة الكتاب '+n(q.page),'btn secondary small',`data-page="${q.page}"`):''}${teacher&&q.answerSourcePage?act('answer-page','مرجع الحل · '+n(q.answerSourcePage),'btn secondary small',`data-page="${q.answerSourcePage}"`):''}</div>`;}
 function sourceViewer(kind,p){
  const total=kind==='answers'?45:136;p=Math.max(1,Math.min(total,Number(p)||1));currentSource={kind,page:p};
  dialog((kind==='answers'?'ملف الإجابات الموافق':'الكتاب المعتمد')+' · '+n(p),`<div class="source-toolbar"><div class="row">${act('source-prev','الصفحة السابقة','btn secondary small',p<=1?'disabled':'')}${act('source-next','الصفحة التالية','btn secondary small',p>=total?'disabled':'')}</div><label for="sourcePageSelect" class="small">الانتقال إلى صفحة</label><select id="sourcePageSelect" class="control" style="width:auto">${Array.from({length:total},(_,i)=>`<option value="${i+1}" ${p===i+1?'selected':''}>${n(i+1)}</option>`).join('')}</select></div><p class="small">${kind==='answers'?'هذه صورة الحل المرفق، وليست إجابة مولّدة. وجود الصفحة لا يعني أن كل بنودها محلولة؛ راجعي العلامة أو الإجابة المكتوبة.':'النص الحرفي والتشكيل والجداول والرسوم كما وردت في الملف المرفوع. رقم الصفحة هو رقمها داخل الملف.'}</p><img class="source-page-image" src="${kind==='answers'?answerImage(p):bookImage(p)}" alt="${kind==='answers'?'صفحة من ملف الإجابات':'صفحة من كتاب اللغة العربية'} رقم ${n(p)}" decoding="async"><div class="row">${act('source-prev','الصفحة السابقة','btn secondary small',p<=1?'disabled':'')}${act('source-next','الصفحة التالية','btn secondary small',p>=total?'disabled':'')}</div>`);
 }

 function dialog(title,html){modal.innerHTML=`<div class="modal-head"><h2>${title}</h2>${act('close',icon('close'),'icon-btn','aria-label="إغلاق النافذة"')}</div><div class="modal-body">${html}</div>`;modal.showModal();}
 function empty(title,text,action=''){return `<div class="empty">${icon('book')}<h3>${title}</h3><p>${text}</p>${action}</div>`;}
 function heading(label,title,desc,action=''){return `<div class="page-heading"><div><span class="eyebrow">${label}</span><h1>${title}</h1><p>${desc}</p></div>${action}</div>`;}
 function source(q){return pill(`${icon('book')}${e(q.sourceLabel)}${q.page?' · ص '+n(q.page):''}`,'wine');}
 function shell(content,r){
  const navs=r.role==='teacher'?[["home","رفيق المعلمة","home"],["curriculum","منهجي","book"],["class","إتقان | 45","clock"],["play","إتقان | PLAY","play"],["library","رفوف","folder"],["review","إجابات الطالبات","users"],["reports","نبض الأسرة","chart"]]:r.role==='student'?[["home","مهمتي اليوم","home"],["curriculum","منهجي","book"],["library","رفوف","folder"],["progress","تقدمي","chart"]]:[["home","نبض الأسرة","chart"]];
  app.innerHTML=`<div class="layout"><aside class="sidebar"><a class="brand" href="#${r.role}/home"><img src="assets/school.webp" alt="شعار مدرسة السلام"><div><strong>إتقان <span style="color:#dcb887">| نبض</span></strong><small>من التدريب إلى الاستقلال</small></div></a><div class="side-label">مساحة ${r.role==='teacher'?'المعلمة':r.role==='student'?'الطالبة':'الأسرة'}</div><nav class="nav" aria-label="التنقل الرئيسي">${navs.map(([page,label,ico])=>`<a href="#${r.role}/${page}" class="${r.page===page||r.page==='lesson'&&page==='curriculum'?'active':''}" ${r.page===page?'aria-current="page"':''}>${icon(ico)}<span>${label}</span>${r.page===page?'<i class="nav-dot"></i>':''}</a>`).join('')}</nav><div class="side-bottom"><div class="side-note">${icon('seed')}<b style="font-size:.81rem"> كل حصة تترك أثرًا</b><p>المنهج أولًا. ثم تدريب هادف، وشاهد مستقل على الفهم.</p></div><div class="side-sign">إعداد: أ. نوف الغرينيق<br>الصف الخامس · الفصل الأول</div></div></aside><div class="stage"><header class="topbar"><div class="context"><span class="avatar">ن</span><div><strong>${r.role==='teacher'?e(D.teacher):r.role==='student'?'أهلًا '+e(student().name):'إتقان | نبض الأسرة'}</strong><small>اللغة العربية · الصف الخامس · <bdi>${D.academicYear}</bdi></small></div></div><div class="mode-switch" aria-label="تبديل دور التجربة">${[['teacher','المعلمة'],['student','الطالبة'],['family','الأسرة']].map(([role,t])=>act('role',t,role===r.role?'active':'',`data-role="${role}"`)).join('')}</div></header><main id="main" class="workspace" tabindex="-1"><div class="demo-banner">${icon('shield')}<span>تجربة قبول بلا تسجيل دخول · أسماء افتراضية · الحفظ على هذا المتصفح فقط، وليس بين الأجهزة.</span><a href="#" data-do="about">حدود النسخة</a></div>${storageWarning?`<div class="notice error">${e(storageWarning)}</div>`:''}${content}<footer class="footnote"><span>${e(D.school)} · مبادرة تعليمية مساندة</span><span>V9 · المنهج المعتمد · لا درجات رسمية في هذه التجربة</span></footer></main></div></div>`;
 }
 function kpis(items){return `<div class="kpis">${items.map(([v,l,i])=>`<div class="kpi"><span class="icon-wrap">${icon(i)}</span><div><b>${v}</b><small>${l}</small></div></div>`).join('')}</div>`;}
 function teacherHome(){
 const l=currentLesson(),pending=S.responses.filter(r=>r.status==='pending').length,active=S.students.filter(s=>C.latest(S,s.id).length).length;
 const plans={class:['في الصف','حصة واضحة.<br>وتعلّم له أثر.','ابدئي من سؤال الكتاب، راقبي الفهم، ثم وجّهي التدريب إلى ما تحتاجه الطالبة.','ابدئي حصة اليوم','teacher/class/'+l.id],home:['في البيت','حضّري مرة.<br>واستفيدي في كل مكان.','اختاري أسئلة الدرس واحفظي ملاحظتك. الحفظ في هذه النسخة على الجهاز نفسه.','جهّزي مهمة الدرس','teacher/lesson/'+l.id],after:['بعد الحصة','إجابة الطالبة<br>تحدد الخطوة التالية.','راجعي الإجابات المفتوحة، ثم اعتمدي التقرير الذي اكتملت شواهده.','راجعي الإجابات','teacher/review']};const p=plans[V.context];
 return heading('رفيق المعلمة','كل ما تحتاجينه… في مسار واحد','المنهج المعتمد كاملًا في خريطته وصفحاته وأنشطته، مع فصل الحل الموثق عن المراجعة البشرية.',act('export',icon('download')+' حفظ بيانات التجربة','btn secondary small'))+`<div class="tabs">${[['home','في البيت'],['class','في الصف'],['after','بعد الحصة']].map(([id,t])=>act('context',t,V.context===id?'active':'',`data-id="${id}"`)).join('')}</div><section class="hero"><div class="hero-copy"><span class="eyebrow">${p[0]} · ${e(l.unitTitle)} · ${e(l.kind)}</span><h1>${p[1]}</h1><p>${p[2]}</p><div class="row">${link(p[4],p[3]+' '+icon('arrow'),'btn light')}${link('student/home','جرّبي رحلة الطالبة','btn ghost')}</div></div><div class="hero-art"><img src="assets/sara.webp" alt="سارة تحمل كتابًا وترتدي مريولًا رصاصيًّا"><div class="hero-badge">${icon('star')} سارة ترافق رحلة التعلم</div></div></section>`+
 kpis([[n(S.assignments.length),'مهام عيّنتِها','send'],[n(active),'حسابات افتراضية شاركت','users'],[n(pending),'إجابات تنتظر المراجعة','book'],[n(D.contentAudit.bookCards),'بطاقات أنشطة الكتاب','folder']])+`<div class="two-col"><div><div class="section-title"><h2>درسك الحالي</h2>${pill('مرجع الصفحة متاح','green')}</div><article class="panel">${chooseLessonMarkup()}<span class="eyebrow">${e(l.unitTitle)} · ص ${pageRange(l)}</span><div class="lesson-title"><div><b>${e(l.title)}</b><small>${e(l.kind)}</small></div></div><div class="row">${pill(n(l.questionCount)+' بطاقة من الكتاب','wine')}${pill(n(l.pages.length)+' صفحات أصلية')}</div><div class="journey"><span>سؤال الكتاب</span><span>تدريب</span><span>مراجعة</span><span>متابعة</span></div>${link('teacher/lesson/'+l.id,'افتحي أسئلة الدرس '+icon('arrow'),'btn full-width')}<div class="row" style="margin-top:12px">${act('read-book','اقرئي المرجع','btn secondary small')}${act('assign-default','تعيين مهمة قصيرة','btn soft small',l.assignableCount?'':'disabled')}</div></article><div class="notice">${n(D.contentAudit.units)} وحدات + مدخل الكتاب. ${n(D.contentAudit.sourcePages)} صفحة أصلية. ملف الإجابات الموافق ليس حلًّا كاملًا لجميع الوحدات.</div></div><div><div class="section-title"><h2>خطوتك التالية</h2></div><div class="panel"><div class="mini-list"><div class="mini-item"><span class="number">١</span><div><h3>اختاري الدرس والمهمة</h3><p>خمس بطاقات مقترحة، أو اختيارك من أسئلة الدرس وفروعه.</p></div></div><div class="mini-item"><span class="number">٢</span><div><h3>جرّبي الإجابة كطالبة</h3><p>يظهر مرجع الدرس الصحيح بجانب السؤال، مع حفظ المحاولة.</p></div></div><div class="mini-item"><span class="number">٣</span><div><h3>راجعي ثم اعتمدي</h3><p>البند بلا مفتاح موثّق ينتظر مراجعتك، ولا يُحتسب خطأً.</p></div></div></div>${link('teacher/review','الإجابات التي تحتاجك '+icon('arrow'),'btn secondary full-width')}</div><div class="panel" style="margin-top:16px"><h3>ملاحظة للدرس القادم</h3><div class="field"><label for="lessonNote" class="small">دون أسماء أو بيانات شخصية حقيقية</label><textarea id="lessonNote" maxlength="1500" placeholder="ما الذي يحتاج إلى متابعة في الحصة القادمة؟">${e(S.notes)}</textarea></div><small>تُحفظ تلقائيًّا على هذا المتصفح.</small></div></div></div><div class="quick-buttons"><a class="quick-card" href="#teacher/class/${l.id}">${icon('clock')}<span><strong>إتقان | 45</strong><small>أسئلة درسك على الشاشة</small></span></a><a class="quick-card" href="#teacher/play">${icon('play')}<span><strong>إتقان | PLAY</strong><small>سباق أسئلة المنهج، ومطابقة وترتيب</small></span></a><a class="quick-card" href="#teacher/library">${icon('folder')}<span><strong>إتقان | رفوف</strong><small>ثلاث قصص أصلية في النسخة الحالية</small></span></a></div>`;
 }
 function curriculum(r){
 const unit=D.units.find(u=>u.id===V.unit)||D.units[1],a=D.contentAudit;
 return heading('منهجي','الكتاب كاملًا، درسًا درسًا','ست وحدات، ومدخل الكتاب، بالترتيب المعتمد. اختاري الدرس لعرض النص وأنشطته ومراجع صفحاته.',act('audit','سجل المحتوى والمطابقة','btn secondary small'))+
 kpis([[n(a.units),'وحدات منهجية','book'],[n(a.lessons)+' + ١','درسًا ومكوّنًا + مدخل الكتاب','folder'],[n(a.bookCards),'بطاقات أنشطة من الكتاب','check'],[n(a.sourcePages),'صفحة أصلية قابلة للعرض','book']])+`<div class="unit-tabs">${D.units.map(u=>act('unit',e(u.title),u.id===V.unit?'active':'',`data-id="${u.id}"`)).join('')}</div><div class="helper-strip"><h2>${unit.title}</h2><div class="row">${act('source-page','محتويات الوحدة وأهدافها','btn secondary small',`data-page="${unit.objectivesPage}"`)}${pill('بداية الوحدة · ص '+n(unit.page))}</div></div><div class="lesson-grid">${unit.lessons.map((l,i)=>`<article class="lesson-row"><span class="number">${n(i+1)}</span><div><span class="eyebrow">${e(l.kind)}</span><h3>${e(l.title)}</h3><small>ص ${pageRange(l)} · ${n(l.questionCount)} بطاقة نشاط</small>${l.requiresAudio||l.requiresVideo?`<p class="small media-warning">${l.requiresAudio?'التسجيل الصوتي توفره المعلمة':'الفيديو توفره المعلمة'}</p>`:''}</div>${link(r.role+'/lesson/'+l.id,'افتحي الدرس '+icon('arrow'),'btn small')}</article>`).join('')}</div><div class="notice">البطاقات تنقل أنشطة الكتاب؛ قد تجمع صفوف جدول أو تفرد فرعًا. عددها ليس عدد أسئلة اختبار ولا نسبة تغطية لمفاتيح الحل. غير المحلول يُراجع بشريًّا ولا يُسجّل خطأً تلقائيًّا.</div><div class="row">${act('source-page','تصفح الكتاب من بدايته','btn secondary',`data-page="1"`)}${r.role==='teacher'?act('registry','تحميل سجل المحتوى','btn secondary'):''}</div>`;
 }
 function lesson(r){
 const l=lessonBy(r.id);if(!l)return empty('لم يُعثر على الدرس','عودي إلى خريطة المنهج.',link(r.role+'/curriculum','منهجي'));
 if(V.lastLesson!==l.id){V.lastLesson=l.id;V.activeLesson=l.id;V.unit=l.unitId;V.tab='book';V.selected=[];V.skill='all';V.query='';S.selectedLesson=l.id;save();}
 const all=lessonQs(l.id,V.tab),qs=all.filter(q=>(V.skill==='all'||q.skill===V.skill)&&(!V.query||C.norm(q.prompt+' '+q.number+' '+q.page).includes(C.norm(V.query))));
 const origins=[['book','من كتابي'],['parallel','أتدرّب'],['independent','أنجز وحدي']].filter(([o])=>lessonQs(l.id,o).length);
 let previousPage=-1;
 return heading('منهجي / '+e(l.unitTitle)+' / '+e(l.kind),e(l.title),'صفحات الدرس: '+pageRange(l)+' · أسئلة الكتاب وفروعه، ومراجع الصفحات الأصلية.',act('read-book',icon('book')+' النص ومرجع الدرس','btn secondary'))+
 `<div class="panel"><div class="row">${pill(n(l.questionCount)+' بطاقة من الكتاب','wine')}${pill('الصفحات الأصلية متاحة','green')}</div><div class="journey"><span>أقرأ الدرس</span><span>أجيب</span><span>أتلقى تغذية راجعة</span><span>أتابع تقدمي</span></div><div class="page-links">${l.pages.map(p=>act('source-page','ص '+n(p),'btn secondary small',`data-page="${p}"`)).join('')}</div><p class="small">صياغة رقمية لأنشطة المصدر؛ بعض الإرشادات مختصرة وبعض الجداول مجموعة في بطاقة. افتحي الصفحة لعرض الأصل كاملًا. نصوص الكتاب بصيغتها، وتعليمات المنصة موجهة للطالبة.</p>${l.mediaNote?`<div class="notice">${e(l.mediaNote)}</div>`:''}</div>
 <div class="tabs">${origins.map(([v,t])=>act('tab',t,V.tab===v?'active':'',`data-id="${v}"`)).join('')}</div><div class="filters"><div class="field"><label for="qSearch">البحث داخل هذا الدرس</label><input id="qSearch" value="${e(V.query)}" placeholder="كلمة من السؤال أو رقم الصفحة" autocomplete="off"></div><div class="field"><label for="qSkill">المهارة</label><select id="qSkill"><option value="all">جميع المهارات</option>${[...new Set(all.map(q=>q.skill))].map(id=>`<option value="${id}" ${V.skill===id?'selected':''}>${e(D.skills[id]||id)}</option>`).join('')}</select></div>${act('filter','بحث','btn secondary')}</div>
 <div class="helper-strip"><span class="small">${n(qs.length)} بطاقة في العرض الحالي</span><div class="row">${r.role==='teacher'?`${act('assign-selected',icon('send')+' تعيين المحدد ('+n(V.selected.length)+')','btn')}${act('select-first','اختيار أول خمسة','btn secondary small')}${link('teacher/class/'+l.id,'عرض الحصة','btn secondary small')}`:`${act('self-practice','تدريب قصير من هذا الدرس '+icon('arrow'),'btn',l.assignableCount?'':'disabled')}`}</div></div>
 <div class="question-list">${qs.map(q=>{const pg=q.page!==previousPage?`<div class="source-section"><h2>صفحة ${n(q.page)}</h2>${act('source-page','عرض الأصل','btn secondary small',`data-page="${q.page}"`)}</div>`:'';previousPage=q.page;return pg+`<article class="question-card" data-question-id="${e(q.id)}"><div class="qhead"><div class="row">${source(q)}${pill(e(D.skills[q.skill]||q.skill))}</div>${r.role==='teacher'&&eligible(q)?`<label class="check"><input type="checkbox" data-pick="${e(q.id)}" ${V.selected.includes(q.id)?'checked':''}><span>للمهمة</span></label>`:''}</div><small class="source-number">${e(String(q.number).replace(/-/g,' / '))}</small><h3 class="question-text">${e(q.prompt)}</h3>${q.type==='mcq'?`<div class="source-options">${q.choices.map((c,i)=>`<span><b>${['أ','ب','ج','د','هـ'][i]||n(i+1)}.</b> ${e(c)}</span>`).join('')}</div>`:''}${q.type==='observation'?'<div class="notice">أداء شفهي أو خطي أو ملاحظة صفية. يُنفّذ وفق المرجع، ولا يُختزل إلى اختيار من متعدد.</div>':q.activityOnly?'<div class="notice">نشاط تأمل في التعلم؛ ليس بندًا لاستخراج نسبة التحصيل.</div>':''}${sourceButtons(q,r.role==='teacher')}${r.role==='teacher'?`<details><summary>${q.autoGraded?'مفتاح التصحيح ومصدره':'مرجع المعلمة · مراجعة بشرية'}</summary><p class="question-text">${e(q.referenceAnswer)}</p>${q.answerSourcePage?act('answer-page','افتحي صورة الحل المرفق','btn secondary small',`data-page="${q.answerSourcePage}"`):''}<p class="small">${q.autoGraded?'يتاح التصحيح الآلي للمفتاح المدخل فقط.':'لن تُرفض إجابة الطالبة تلقائيًّا في هذا البند. تحتاج إلى مراجعة المعلمة.'}</p>${q.answerStatus==='source_conflict_manual'?'<p class="notice">يوجد اختلاف بين وصف المصدر ووصف الحل؛ لا تُعتمد المقارنة آليًّا.</p>':''}</details>`:''}</article>`;}).join('')||empty('لا توجد نتائج مطابقة','غيّري البحث أو المهارة.')}</div>`;
 }
 function assignDialog(ids,kind='training',storyId=null){
  const selected=ids.filter(id=>{const q=qby(id);return q&&!q.needsContentReview&&q.type!=='observation';});
  if(!selected.length)return notify('اختاري سؤالًا واحدًا على الأقل.');
  if(selected.length>12)return notify('اختاري اثني عشر سؤالًا أو أقل للمهمة الواحدة.');
  const meta=lessonBy(qby(selected[0])?.lesson)||currentLesson();const title=storyId?'رفوف · '+D.stories.find(s=>s.id===storyId).title:meta.title+(kind==='independent'?' · أداء مستقل':' · مهمة من كتابي');
  dialog('تعيين مهمة قصيرة',`<form id="assignForm" class="form-stack"><div class="notice">هذه حسابات افتراضية للتجربة. لا تدخلي أسماء طالباتك الحقيقية.</div><div class="field"><label for="assignTitle">عنوان المهمة</label><input id="assignTitle" value="${e(title)}" maxlength="120" required></div><div class="row">${pill(n(selected.length)+' أسئلة','wine')}${pill(kind==='independent'?'بلا تلميحات أو إعادة محاولة':'تدريب مع تلميحات')}</div><div><b class="small">تظهر المهمة للطالبات المحددات:</b><div class="check-grid">${S.students.map(s=>`<label class="check"><input name="target" type="checkbox" value="${s.id}" checked>${s.name} · حساب افتراضي</label>`).join('')}</div></div>${selected.some(id=>qby(id).requiresAudio||qby(id).requiresVideo)?`<div class="notice"><label class="check"><input id="mediaAcknowledged" type="checkbox" required>سأوفر المسموع أو المقطع الأصلي للطالبة قبل هذا التكليف.</label></div>`:''}<input type="hidden" id="assignIds" value="${e(JSON.stringify(selected))}"><input type="hidden" id="assignKind" value="${kind}"><input type="hidden" id="assignStory" value="${storyId||''}"><button class="btn" type="submit">${icon('send')} تعيين المهمة</button><p id="assignError" role="alert" class="small"></p></form>`);
 }
 function learnerControl(){return `<div class="helper-strip screen-only"><label class="small" for="learnerSelect">اختاري حساب التجربة</label><select class="control" id="learnerSelect" style="width:auto">${S.students.map(s=>`<option value="${s.id}" ${V.learner===s.id?'selected':''}>${s.name} · افتراضية</option>`).join('')}</select></div>`;}
 function assignmentCard(a){const done=a.questionIds.filter(qid=>C.attempts(S,V.learner,a.id,qid).length).length;return `<article class="assignment-card"><div>${pill(a.kind==='independent'?'أداء مستقل':a.kind==='story'?'رفوف':'منهجي','wine')}<h3>${e(a.title)}</h3><small>${n(done)} من ${n(a.questionIds.length)} أسئلة أُجيبت · ${a.kind==='independent'?'محاولة واحدة':'تدريب موجّه'}</small></div>${link('student/task/'+a.id,(done?'استكملي أو راجعي':'ابدئي المهمة')+' '+icon('arrow'),'btn')}</article>`;}
 function studentHome(){const sum=C.summary(S,D,V.learner),as=S.assignments.filter(a=>a.studentIds.includes(V.learner));return learnerControl()+`<section class="hero"><div class="hero-copy"><span class="eyebrow">رحلتك تبدأ بخطوة</span><h1>أهلًا يا ${e(student().name)}.<br>نقرأ، نفهم، ثم نتقدم.</h1><p>ابدئي بمهمة قصيرة. خذي وقتك في القراءة، وعودي إلى النص كلما احتجتِ إلى دليل.</p><div class="row">${as.length?link('student/task/'+as[as.length-1].id,'افتحي مهمتي '+icon('arrow'),'btn light'):act('student-demo','جهزي مهمة التجربة','btn light')}${link('student/library','اختاري قصة','btn ghost')}</div></div><div class="hero-art"><img src="assets/sara.webp" alt="سارة ترافقك في القراءة"></div></section>`+kpis([[n(sum.points),'نقاط فهم، وليست درجات','star'],[n(as.length),'مهام متاحة','book'],[n(sum.pending),'إجابات لدى المعلمة','users'],[n(sum.completedStories),'تحديات قصص أُكملت','folder']])+`<div class="section-title"><h2>مساري اليوم</h2>${pill('لا مقارنة مع زميلاتك','green')}</div>${as.length?as.map(assignmentCard).join(''):empty('مهمتك الأولى في انتظارك','عيّني مهمة من لوحة المعلمة، أو أنشئي مهمة التجربة بالحساب الافتراضي.',act('student-demo','بدء مهمة التجربة','btn'))}<div class="notice">فتح القصة وحده لا يمنح نقاطًا. تُمنح النقاط للإجابة الصحيحة، ومراجعة الإجابة المفتوحة تكون لدى المعلمة.</div>`;}
 function bookMarkup(story=null,focus=[],lessonId=null,questionPage=null){
 const l=lessonBy(lessonId||currentLesson().id)||currentLesson(),reading=story||D.lessonContent[l.id],paragraphs=reading?.paragraphs||[];
 const pages=story?[]:(reading?.pages||[l.id==='u0-l1'?10:l.startPage]);
 return `<article class="reading-pane"><div class="reading-tools"><div><span class="eyebrow">${story?'رفوف · قصة أصلية':e(l.unitTitle)+' · '+e(l.kind)}</span><h3>${e(reading?.title||l.title)}</h3></div><div class="row">${act('font-minus','أ−','','aria-label="تصغير خط القراءة"')}${act('font-plus','أ+','','aria-label="تكبير خط القراءة"')}</div></div>${!story?`<div class="page-links">${pages.map(p=>act('source-page','أصل النص · ص '+n(p),'btn secondary small',`data-page="${p}"`)).join('')}${questionPage&&!pages.includes(questionPage)?act('source-page','مرجع السؤال · ص '+n(questionPage),'btn secondary small',`data-page="${questionPage}"`):''}</div>`:''}${l.mediaNote&&!story?`<div class="notice">${e(l.mediaNote)}</div>`:''}${paragraphs.length?`<div class="story-text ${reading.poem?'poem-text':''}" style="--reading-font:${V.font}px">${paragraphs.map((p,i)=>`<p class="${focus.includes(i)?'focused':''}">${text(p)}</p>`).join('')}</div>`:`<div class="notice">اقرئي الفقرة والأمثلة في صفحة الدرس الأصلية. يمكنك تكبير الصفحة وفتح صفحة السؤال.</div><img class="source-inline-image" src="${bookImage(pages[0])}" alt="مرجع درس ${e(l.title)}، صفحة ${n(pages[0])}" loading="lazy" decoding="async">`}<small>${story?e(story.origin):(reading?.author?e(reading.author)+' · ':'')+'من الكتاب المعتمد. الشكل الطباعي والتشكيل الكامل محفوظان في صورة الأصل.'}</small></article>`;
 }
 function quiz(r){
  const a=S.assignments.find(x=>x.id===r.id);if(!a||!a.studentIds.includes(V.learner))return learnerControl()+empty('هذه المهمة غير متاحة لهذا الحساب','اختاري الحساب الذي عُيّنت له المهمة، أو عودي إلى مسارك.',link('student/home','مهمتي اليوم'));
  if(V.quizId!==a.id){V.quizId=a.id;V.qi=0;V.selection=null;V.retry=false;V.hinted=false;}
  const done=a.questionIds.filter(qid=>C.attempts(S,V.learner,a.id,qid).length>0).length;
  if(V.qi>=a.questionIds.length)return quizResult(a);
  const q=qby(a.questionIds[V.qi]),previous=C.attempts(S,V.learner,a.id,q.id),last=previous.at(-1),ind=a.kind==='independent',locked=!!last&&!V.retry,draftKey=`${V.learner}|${a.id}|${q.id}`,draft=S.drafts[draftKey]??'',story=D.stories.find(s=>s.id===a.storyId);
  let feedback='';if(locked){if(ind)feedback='<div class="notice success">حُفظت إجابتك. أكملي المهمة قبل الاطلاع على النتائج.</div>';else if(last.status==='pending')feedback='<div class="notice">وصلت إجابتك إلى المعلمة للمراجعة. لم تُحتسب خطأ.</div>';else if(last.score===2)feedback='<div class="notice success">أحسنتِ. إجابتك صحيحة.'+(last.comment?' '+e(last.comment):'')+'</div>';else if(last.status==='reviewed')feedback=`<div class="notice">مراجعة المعلمة: ${n(last.score)} من ٢. ${e(last.comment||'راجعي المعنى والدليل قبل مهمة جديدة.')}</div>`;else feedback=`<div class="notice">${previous.length<3?'لم تصلي إلى الإجابة بعد. عودي إلى النص ثم جرّبي مرة أخرى.':'انتهت محاولات هذا السؤال. سنحتاج إلى تدريب آخر، لا إلى تكرار التخمين.'}</div>`;}
  const selection=locked?last.value:V.selection;
  return heading('رحلة الطالبة / '+e(a.title),ind?'أنجز وحدي':'أقرأ وأجيب',ind?'هذا أداء مستقل: لا تلميحات، ومحاولة واحدة لكل سؤال.':'اقرئي النص، ثم أجيبي. يمكنك العودة إلى الفقرة المرتبطة بالسؤال.',link('student/home','العودة إلى مساري','btn secondary small'))+`<div class="book-layout">${bookMarkup(story,!ind&&V.hinted?(q.evidence||[]):[],q.lesson,q.page)}<section class="quiz-panel"><div class="quiz-progress-text"><span>السؤال ${n(V.qi+1)} من ${n(a.questionIds.length)}</span><span>${n(done)} إجابات محفوظة</span></div><div class="progress"><span style="width:${done/a.questionIds.length*100}%"></span></div><div class="row">${source(q)}${pill(D.skills[q.skill])}</div><h2 class="question-text">${e(q.prompt)}</h2>${q.requiresAudio?'<div class="notice">أجيبي بعد الاستماع إلى التسجيل الأصلي الذي توفره المعلمة.</div>':''}<form id="answerForm" data-aid="${a.id}" data-qid="${e(q.id)}">${q.type==='mcq'?`<div class="choice-grid">${q.choices.map((ch,i)=>act('choose',`<span class="letter">${['أ','ب','ج','د','هـ'][i]||n(i+1)}</span><span>${e(ch)}</span>`,'choice '+(selection===i?'selected':''),`data-index="${i}" aria-pressed="${selection===i}" ${locked?'disabled':''}`)).join('')}</div>`:`<div class="field"><label for="answerText">إجابتك</label><textarea id="answerText" maxlength="3000" ${locked?'disabled':''} placeholder="اكتبي المعنى بأسلوبك، مع الدليل عندما يطلب السؤال ذلك.">${e(locked?last.value:draft)}</textarea><small>قد تختلف صياغتك عن المرجع وتكون صحيحة؛ المعلمة تراجع المعنى.</small></div>`}${V.hinted&&!ind?`<div class="notice">${e(q.hint||'حددي الحدث المرتبط بالسؤال في النص. لا تختاري قبل أن تجدي الدليل.')}</div>`:''}${feedback}<p id="answerError" role="alert" class="small"></p><div class="quiz-actions">${!locked?'<button type="submit" class="btn">حفظ الإجابة '+icon('check')+'</button>':''}${!locked&&!ind?act('hint','أحتاج تلميحًا','btn secondary'):''}${locked&&last.score===0&&previous.length<3&&!ind&&last.status!=='reviewed'?act('retry','أعيدي المحاولة','btn secondary'):''}${locked?act('next-question',V.qi===a.questionIds.length-1?'عرض نتيجة المهمة':'السؤال التالي '+icon('arrow'),'btn'):''}</div></form><div class="quiz-pagination">${a.questionIds.map((id,i)=>act('jump-question',n(i+1),i===V.qi?'active':'',`data-index="${i}" aria-label="انتقلي إلى السؤال ${n(i+1)}"`)).join('')}</div><p class="small" style="margin-top:16px">تُحفظ الإجابة على هذا المتصفح. النقاط مستقلة عن الإتقان والدرجات المدرسية.</p></section></div>`;
 }
 function quizResult(a){const rs=a.questionIds.map(id=>C.attempts(S,V.learner,a.id,id).at(-1)).filter(Boolean),graded=rs.filter(r=>r.score!==null),pending=rs.filter(r=>r.score===null).length;return heading('رحلة الطالبة','انتهت هذه الخطوة','راجعي ما فعلتِه، ثم اختاري خطوة تالية.')+`<div class="panel"><span class="eyebrow">${e(a.title)}</span><h2 style="margin-top:12px">كل إجابة تساعدنا على معرفة خطوتك التالية.</h2><div class="stat-grid"><div class="stat-box"><b>${n(rs.length)} / ${n(a.questionIds.length)}</b><small>أسئلة أُجيبت</small></div><div class="stat-box"><b>${n(graded.reduce((t,r)=>t+r.score,0))} / ${n(graded.length*2)}</b><small>حصيلة البنود المصححة</small></div><div class="stat-box"><b>${n(pending)}</b><small>بانتظار المعلمة</small></div></div><div class="question-list">${a.questionIds.map((id,i)=>{const q=qby(id),rr=rs.find(r=>r.questionId===id);return `<div class="question-card"><div class="row">${pill(D.skills[q.skill],'wine')}${pill(!rr?'لم تجيبي بعد':rr.score===null?'بانتظار المراجعة':rr.score===2?'إجابة صحيحة':'تحتاج متابعة',rr?.score===2?'green':'gold')}</div><h3 style="margin:10px 0">${q.prompt}</h3>${rr?.comment?`<p class="small">${e(rr.comment)}</p>`:''}${act('jump-question','راجعي السؤال','btn secondary small',`data-index="${i}"`)}</div>`;}).join('')}</div><div class="notice">نتيجة هذه المهمة ليست حكمًا نهائيًّا على إتقان المهارة. نحتاج إلى شواهد مستقلة لاحقة.</div><div class="row">${link('student/library','أختار قصة من رفوف','btn')}${link('student/home','أعود إلى مساري','btn secondary')}</div></div>`;}
 function library(r){return (r.role==='student'?learnerControl():'')+heading('إتقان | رفوف','كل قصة… تفتح لك نافذة','مكتبة البداية: ثلاث قصص أصلية للتجربة، بأسئلة معدّة مسبقًا ومعلومة المصدر.')+`<div class="three-col">${D.stories.map((s,i)=>`<article class="story-card"><div class="book-cover ${i===1?'two':i===2?'three':''}"><small>إتقان | رفوف</small>${icon(s.symbol)}<h3>${s.title}</h3><small>${s.subtitle}</small></div><div class="book-info"><div class="row">${pill(s.level)}${pill(n(s.time)+' دقائق مقترحة')}${pill('٣ أسئلة','wine')}</div><p class="small">${D.skills[s.skill]} · ${n(s.paragraphs.join(' ').split(/\s+/).length)} كلمة تقريبًا</p>${link(r.role+'/story/'+s.id,'افتحي القصة '+icon('arrow'),'btn secondary')}${r.role==='teacher'?act('assign-story','تعيين هذه القصة','btn soft small',`data-id="${s.id}"`):''}</div></article>`).join('')}</div><div class="notice">الأسئلة في هذه المكتبة ليست توليدًا حيًّا بالذكاء الاصطناعي. رفع الصور وتوليد أسئلة جديدة غير مفعّلين في تجربة القبول الحالية.</div>`;}
 function story(r){const s=D.stories.find(s=>s.id===r.id);if(!s)return empty('القصة غير موجودة','عودي إلى مكتبتك.',link(r.role+'/library','رفوف'));return heading('رفوف / '+s.level,s.title,s.subtitle,link(r.role+'/library','العودة إلى رفوف','btn secondary small'))+`<div class="two-col">${bookMarkup(s)}<div class="panel"><span class="eyebrow">تحدي القصة</span><h2 style="margin:12px 0">اقرئي لتكتشفي،<br>ثم أجيبي لتتقدمي.</h2><p class="small">ثلاثة أسئلة تقيس فهمك لهذا النص. العودة إلى القصة مسموحة، ولا تُمنح نقاط لمجرد فتحها.</p><div class="mini-list">${s.questions.map((q,i)=>`<div class="mini-item"><span class="number">${n(i+1)}</span><div><h3>${D.skills[q.skill]}</h3><p>${r.role==='teacher'?q.prompt:'ابحثي عن المعنى والدليل أثناء القراءة.'}</p></div></div>`).join('')}</div><div style="margin-top:22px">${r.role==='teacher'?act('assign-story','تعيين القصة للطالبات '+icon('send'),'btn full-width',`data-id="${s.id}"`):act('story-challenge','قرأت القصة، أبدأ التحدي '+icon('arrow'),'btn full-width',`data-id="${s.id}"`)}</div></div></div>`;}
 function reviewPage(){const pending=S.responses.filter(r=>r.status==='pending');return heading('متابعة التعلم','إجابات الطالبات','راجعي المعنى والدليل. الإجابة المعلّقة لا تُحتسب خطأً.',pill(n(pending.length)+' إجابات للمراجعة','wine'))+(pending.length?`<div class="question-list">${pending.map(r=>{const q=qby(r.questionId),st=S.students.find(x=>x.id===r.studentId);return `<article class="question-card"><div class="qhead"><h3>${st.name} · حساب افتراضي</h3>${source(q)}</div><p>${q.prompt}</p><div class="review-answer">${e(q.type==='mcq'?q.choices[r.value]:r.value)}</div>${sourceButtons(q,true)}<details><summary>مرجع الإجابة ومعيار المراجعة</summary><p>${e(q.referenceAnswer)}</p><p>درجتان: معنى صحيح يفي بالمطلوب. درجة: معنى جزئي أو دليل ناقص. صفر: لم يظهر المعنى المطلوب بعد.</p></details><div class="field" style="margin:15px 0"><label for="comment-${r.id}">تغذية راجعة للطالبة</label><input id="comment-${r.id}" maxlength="600" placeholder="مثال: المعنى صحيح؛ أضيفي الجملة التي تثبته."></div><div class="grade-row">${[[2,'إجابة مستوفية · ٢'],[1,'إجابة جزئية · ١'],[0,'تحتاج تدريبًا · ٠']].map(([sc,label])=>act('grade',label,sc===2?'btn':'btn secondary',`data-id="${r.id}" data-score="${sc}"`)).join('')}</div></article>`;}).join('')}</div>`:empty('لا توجد إجابات معلّقة','ستظهر هنا الإجابات المفتوحة بعد أن تجيب عنها الطالبة.',link('student/home','جرّبي بوابة الطالبة')))+`<div class="section-title"><h2>شواهد التعلم الحالية</h2></div><div class="panel">${S.students.map(st=>{const x=C.summary(S,D,st.id);return `<div class="report-summary-row"><span class="rounded-letter">${st.name[0]}</span><div><h3>${st.name}</h3><small>${n(x.graded)} بنود مصححة · ${n(x.pending)} معلّقة · ${n(x.independentCount)} في الأداء المستقل</small></div>${pill(x.graded?'شواهد محدودة، لا حكم نهائي':'لم تتوفر بيانات',x.graded?'green':'gold')}</div>`;}).join('')}</div>`;}
 function reportMarkup(x,published=false){return `<article class="report"><div class="report-brand"><img src="assets/school.webp" alt="شعار مدرسة السلام"><div><h2>إتقان | نبض الأسرة</h2><small>${e(D.school)}</small></div></div><span class="eyebrow">تقرير تجربة · ليس تقرير طالبة حقيقية</span><h1 style="margin:10px 0">${e(x.student.name)} · الصف الخامس</h1><p class="muted">ما الذي ظهر في التعلم؟ وما الخطوة التي تساعدنا بعدها؟</p><div class="stat-grid"><div class="stat-box"><b>${n(x.graded)}</b><small>بنود مصححة</small></div><div class="stat-box"><b>${n(x.independentCount)}</b><small>بنود أداء مستقل</small></div><div class="stat-box"><b>${n(x.points)}</b><small>نقاط تحفيزية</small></div></div>${x.rows.length?`<table class="report-table"><thead><tr><th>المهارة</th><th>حصيلة البنود</th><th>عدد الشواهد</th></tr></thead><tbody>${x.rows.map(row=>`<tr><td>${D.skills[row.skill]}</td><td>${n(row.score)} من ${n(row.max)}</td><td>${n(row.count)}</td></tr>`).join('')}</tbody></table>`:'<div class="notice">لا توجد شواهد مصححة بعد.</div>'}<div class="notice"><b>كيف أساند ابنتي؟</b><p>${x.recommendation}</p></div><p>رفوف: ${n(x.completedStories)} تحديات قصص مكتملة. لا نستنتج عدد الكتب المقروءة من فتح الصفحات وحده.</p><p class="report-note">هذه حصيلة بنود مختلفة في التدريب والقراءة والأداء المستقل، وليست قياسًا معياريًّا أو إثباتًا سببيًّا لرفع التحصيل. لا تُدرج في الدرجات الرسمية. النتائج مبنية على بيانات التجربة فقط.</p><div class="report-stamp">${published?'لقطة معتمدة في التجربة':'معاينة غير منشورة'} · ${x.generatedAt?e(new Date(x.generatedAt).toLocaleString('ar-QA')):'لم تُعتمد بعد'}</div></article>`;}
 function reports(){const sums=readiness(),ready=sums.filter(s=>s.graded&&!s.pending);return heading('نبض الأسرة','تقرير واضح. واعتماد جماعي.','لا رسائل فردية هنا: اعتمدي التقارير الجاهزة، وأجّلي الحالات التي تنتظر مراجعتك.',act('publish-reports','اعتماد الجاهز ('+n(ready.length)+') '+icon('check'),'btn',!ready.length?'disabled':''))+`<div class="panel screen-only">${sums.map(x=>`<div class="report-summary-row"><span class="rounded-letter">${x.student.name[0]}</span><div><h3>${x.student.name} · افتراضية</h3><small>${x.pending?n(x.pending)+' إجابات تنتظر المراجعة':x.graded?n(x.graded)+' بنود مصححة':'لا توجد بيانات بعد'}</small></div>${pill(x.pending?'تحتاج مراجعتك':x.graded?'جاهز للاعتماد':'لا يصدر تقرير بلا بيانات',x.pending?'gold':x.graded?'green':'')}${act('view-report','معاينة','btn secondary small',`data-id="${x.student.id}"`)}</div>`).join('')}</div><div class="notice screen-only">لا يوجد إرسال تلقائي إلى منصة قطر للتعليم. في النسخة التشغيلية ستكون هي قناة الإعلان؛ هذا تبويب محاكاة للتقارير فقط.</div><div class="section-title screen-only"><h2>معاينة تقرير ${e(S.students.find(s=>s.id===V.reportStudent).name)}</h2><div class="row">${act('print',icon('print')+' طباعة أو حفظ PDF','btn secondary small')}${link('family/home','معاينة بوابة الأسرة','btn secondary small')}</div></div>${reportMarkup(C.summary(S,D,V.reportStudent),false)}`;}
 function family(){const st=S.students.find(x=>x.id===V.reportStudent),report=S.reports[st.id];return heading('نبض الأسرة','نافذة صغيرة على التعلم','تعرض هذه الصفحة نموذجًا افتراضيًّا. لا تستخدم لتقارير حقيقية قبل تفعيل التحقق والصلاحيات.')+`<div class="notice screen-only">هذا تبديل بين شخصيات العرض، وليس تحققًا من هوية ولي الأمر. البيانات افتراضية بالكامل.</div><div class="helper-strip screen-only"><label for="familySelect" class="small">شخصية العرض</label><select id="familySelect" class="control" style="width:auto">${S.students.map(x=>`<option value="${x.id}" ${x.id===st.id?'selected':''}>${x.name} · افتراضية</option>`).join('')}</select>${act('print',icon('print')+' طباعة','btn secondary small',!report?'disabled':'')}</div>${report?reportMarkup(report,true):empty('لم يُعتمد تقرير لهذه الشخصية بعد','تظهر النتيجة هنا بعد وجود إجابات مصححة واعتماد التقرير من لوحة المعلمة.',link('teacher/reports','العودة إلى اعتماد التقارير'))}`;}
 function progress(){const x=C.summary(S,D,V.learner);return learnerControl()+heading('تقدمي','أتقدم مقارنة بنفسي','النقاط تشجعك، والشواهد المستقلة تساعد معلمتك على معرفة ما تعلمتِه.')+kpis([[n(x.points),'نقاطك','star'],[n(x.graded),'إجابات مصححة','check'],[n(x.pending),'بانتظار المراجعة','users'],[n(x.completedStories),'تحديات قصص أُكملت','book']])+`<div class="panel">${x.rows.length?x.rows.map(row=>`<div class="mini-item"><span class="number">${icon('seed')}</span><div style="flex:1"><h3>${D.skills[row.skill]}</h3><p>${n(row.score)} من ${n(row.max)} في ${n(row.count)} بنود. نحتاج شواهد أخرى قبل الحكم على الإتقان.</p><div class="progress"><span style="width:${row.percent}%"></span></div></div></div>`).join(''):empty('أول خطوة تصنع البداية','أجيبي عن مهمة لتظهري تقدمك هنا.',link('student/home','مهمتي اليوم'))}</div>`;}
 const phases=[['تهيئة',3],['قراءة ونمذجة',10],['تدريب موجّه',12],['تطبيق مستقل',12],['تحقق من الفهم',5],['إغلاق الدرس',3]];
 function classPage(){
 const rid=route().id;if(rid&&lessonBy(rid))V.activeLesson=rid;const l=currentLesson(),qs=lessonQs(l.id).filter(q=>!q.activityOnly);V.classIndex=Math.min(V.classIndex,Math.max(0,qs.length-1));const q=qs[V.classIndex];let start=0;const phase=phases.findIndex(p=>{start+=p[1]*60;return V.time<start;});
 return heading('إتقان | 45','حصة '+e(l.title),'اسألي عند الحاجة، وسجلي الملاحظة. لا يلزم جهاز لكل طالبة.',act('board',icon('fullscreen')+' وضع السبورة','btn secondary'))+`<div class="panel screen-only">${chooseLessonMarkup(l.id)}</div><div class="timeline">${phases.map((p,i)=>`<div class="time-slot ${i===phase?'active':''}"><b>${p[0]}</b><small>${n(p[1])} دقائق</small></div>`).join('')}</div><div class="two-col"><div class="panel"><span class="eyebrow">من أسئلة الدرس · ${n(V.classIndex+1)} من ${n(qs.length)}</span><div class="class-question-nav">${act('class-prev','السابق','btn secondary small',V.classIndex===0?'disabled':'')}${act('class-next','التالي','btn secondary small',V.classIndex>=qs.length-1?'disabled':'')}</div>${q?`<div class="row">${source(q)}${pill(e(D.skills[q.skill]))}</div><h2 class="question-text class-question">${e(q.prompt)}</h2>${q.type==='mcq'?`<div class="source-options">${q.choices.map((c,i)=>`<span><b>${['أ','ب','ج','د','هـ'][i]||n(i+1)}.</b> ${e(c)}</span>`).join('')}</div>`:''}${sourceButtons(q,true)}<details class="notice"><summary>مرجع المعلمة</summary><p>${e(q.referenceAnswer)}</p></details>`:''}${l.mediaNote?`<div class="notice">${e(l.mediaNote)}</div>`:''}<div class="observation-grid">${S.students.map(s=>`<div class="observation-row"><b>${s.name}</b><div class="row">${act('observe','ظهر الفهم','btn '+(V.observation[l.id+'|'+s.id]==='yes'?'':'secondary')+' small',`data-id="${l.id}|${s.id}" data-value="yes"`)}${act('observe','تحتاج متابعة','btn '+(V.observation[l.id+'|'+s.id]==='follow'?'':'secondary')+' small',`data-id="${l.id}|${s.id}" data-value="follow"`)}</div></div>`).join('')}</div><div class="notice">ملاحظات أداء صفية، لا درجة اختبار ولا إثبات إتقان. لا تُمنح نقاط فردية من إجابة جماعية.</div><div class="row">${act('start-game','تدريب جماعي في PLAY','btn',`data-id="race"`)}${link('teacher/lesson/'+l.id,'اختيار مهمة للمتابعة','btn secondary')}</div></div><div class="panel" style="text-align:center"><span class="eyebrow">زمن الحصة المتبقي</span><div id="classTimer" class="timer" style="margin-top:22px">${timeText(2700-V.time)}</div><small>الخطة المقترحة مجموعها ٤٥ دقيقة</small><div class="timer-controls">${act('toggle-timer',icon(V.running?'pause':'play')+(V.running?'إيقاف مؤقت':'بدء المؤقت'),'btn')}${act('reset-timer',icon('refresh'),'icon-btn','aria-label="إعادة المؤقت"')}</div><div class="hr"></div><h3>متابعة قصيرة دون تعطيل الحصة</h3><p class="small" style="margin-top:12px">حين تحتاج قلة إلى دعم، سجلي المتابعة وأكملي هدف الحصة، ثم عيّني تدريبًا مناسبًا.</p>${act('read-book','مرجع الدرس','btn secondary full-width')}</div></div>`;
 }
 function timeText(v){v=Math.max(0,Math.floor(v));return String(Math.floor(v/60)).padStart(2,'0')+':'+String(v%60).padStart(2,'0');}
 function play(){const selected=currentLesson();const games=[['match','جسر المفردات','صلي الكلمة بمعناها. اختياران صحيحان يبنيان الجسر.','link','المفردة من السياق'],['order','خيط الحكاية','رتبي أحداث «المستقبل» حتى تتضح علاقة البداية بالنهاية.','flag','ترتيب الأحداث'],['race','سباق أسئلة المنهج','يتبادل فريقان الإجابة عن أسئلة الدرس المختار. المعلمة تعتمد البند الذي ليس له مفتاح موثق.','play',selected.title]];return heading('إتقان | PLAY','اللعب يخدم المهارة','سباق أسئلة الدرس المختار، مع مطابقة المفردات وترتيب أحداث المستقبل.')+`<div class="panel">${chooseLessonMarkup(selected.id)}<p class="small">اختيار الدرس يغيّر محتوى السباق. المطابقة والترتيب مرتبطان بقصة «المستقبل» فقط؛ لم نسمّ نسخ الأسئلة ألعابًا مستقلة.</p></div><div class="three-col">${games.map(([id,title,desc,ico,skill])=>`<article class="game-card"><span class="game-icon">${icon(ico)}</span><span class="eyebrow">${skill}</span><h2>${title}</h2><p>${desc}</p><div class="row">${pill('شاشة واحدة للفصل')}${pill('٣ دقائق مقترحة','wine')}</div>${act('start-game','تشغيل اللعبة '+icon('arrow'),'btn',`data-id="${id}"`)}</article>`).join('')}</div><div class="notice">نتيجة اللعب الجماعي لا تُنسب إلى كل طالبة. العودة إلى الأداء المستقل مطلوبة قبل إصدار حكم فردي.</div><div class="section-title"><h2>جلسات اللعب على هذا الجهاز</h2></div><div class="panel">${S.games.length?S.games.slice(-6).reverse().map(g=>`<div class="mini-item">${icon('play')}<div><h3>${e(g.title)}</h3><p>${g.completed?'اكتمل التحدي':'اختُتم مبكرًا'} · ${n(g.points)} نقطة لعب جماعي · لم تُضف إلى نقاط الطالبات.</p></div></div>`).join(''):empty('لم تكتمل جلسة لعب بعد','شغلي لعبة واختتمي الجلسة لتظهر هنا.')}</div>`;}
 function initGame(type){const l=currentLesson(),pool=lessonQs(l.id).filter(q=>!q.activityOnly),ids=(pool.filter(q=>q.type!=='observation').length?pool.filter(q=>q.type!=='observation'):pool).slice(0,5).map(q=>q.id);V.game={id:uid('game'),type,lessonId:l.id,questionIds:ids,points:0,matched:[],left:null,right:null,notice:'',order:[2,0,3,1],team:0,teams:[0,0],qi:0,selected:null,answered:false,done:false,logged:false};go('teacher/game/'+type);}
 function game(r){const g=V.game;if(!g||g.type!==r.id)return empty('اختاري لعبة من المكتبة','لا تحتاج هذه الألعاب إلى حساب طالبة.',link('teacher/play','مكتبة PLAY'));
 const titles={match:'جسر المفردات',order:'خيط الحكاية',race:'سباق الصف'};let html='';
 if(g.type==='match'){
  const pairs=[['هادر','عالي الصوت'],['حانق','غاضب'],['الارتواء','الاكتفاء من الماء']];
  html=`<p class="muted" style="margin-top:13px">اختاري كلمة من العمود الأول، ثم اختاري معناها. المحتوى مرتبط بنص «المستقبل»، ص ١٩.</p><div class="matching"><div>${pairs.map(([w],i)=>act('match-left',w,'match-tile '+(g.matched.includes(i)?'matched':'')+(g.left===i?' selected':''),`data-index="${i}" ${g.matched.includes(i)?'disabled':''}`)).join('')}</div><div>${[2,0,1].map(i=>act('match-right',pairs[i][1],'match-tile '+(g.matched.includes(i)?'matched':'')+(g.right===i?' selected':''),`data-index="${i}" ${g.matched.includes(i)?'disabled':''}`)).join('')}</div></div><div class="progress"><span style="width:${g.matched.length/3*100}%"></span></div><p>${n(g.matched.length)} من ٣ روابط صحيحة · ${n(g.points)} نقطة لعب</p>`;
 }else if(g.type==='order'){
  const events=['نظرت الشجرة إلى قلة ماء النهر وتوقعت موته.','أخبرها النهر أن الصيف سيرحل ويأتي الشتاء.','أقبل الشتاء فازداد الماء، واعترفت الشجرة بخطئها.','دفع النهر ماءه نحو الشجرة حتى ارتوت.'];
  html=`<p class="muted" style="margin-top:13px">رتبي الأحداث بأزرار الأعلى والأسفل. جمل الترتيب تلخيص من إعداد إتقان، لا نقل حرفي لسؤال الكتاب.</p><div class="sort-list">${g.order.map((id,i)=>`<div class="sort-row"><span class="pill wine">${n(i+1)}</span><p>${events[id]}</p>${act('order-up',icon('up'),'icon-btn',`data-index="${i}" aria-label="رفع الحدث ${n(i+1)}" ${i===0||g.done?'disabled':''}`)}${act('order-down',icon('down'),'icon-btn',`data-index="${i}" aria-label="خفض الحدث ${n(i+1)}" ${i===3||g.done?'disabled':''}`)}</div>`).join('')}</div>${act('check-order','تحققي من خيط الحكاية '+icon('check'),'btn light',g.done?'disabled':'')}`;
 }else{

  const qs=g.questionIds,q=qby(qs[Math.min(g.qi,qs.length-1)]),meta=lessonBy(g.lessonId);
  html=`<div class="race-tracks">${['فريق الأمل','فريق الإبداع'].map((t,i)=>`<div class="race-track"><div class="row"><b>${t}</b><span>${n(g.teams[i])} نقاط</span></div><div class="progress"><span style="width:${Math.min(g.teams[i]/Math.max(10,qs.length*10)*100,100)}%"></span></div></div>`).join('')}</div><div class="race-teams">${['فريق الأمل','فريق الإبداع'].map((t,i)=>act('team',t,g.team===i?'active':'',`data-index="${i}" ${g.answered?'disabled':''}`)).join('')}</div><small class="game-source-label">${e(meta.title)} · السؤال ${n(g.qi+1)} من ${n(qs.length)} · ص ${n(q.page)}</small><h2 class="question-text" style="margin:15px 0">${e(q.prompt)}</h2>${q.requiresAudio||q.requiresVideo?'<div class="notice">شغّلي المسموع أو الفيديو الأصلي قبل هذا التحدي.</div>':''}${q.type==='mcq'?`<div class="choice-grid">${q.choices.map((ch,i)=>act('race-answer',e(ch),'choice '+(g.selected===i?'selected':''),`data-index="${i}" ${g.answered?'disabled':''}`)).join('')}</div>`:'<p>تجيب المجموعة شفهيًّا أو كتابةً، وتراجع المعلمة استيفاء المطلوب.</p>'}${sourceButtons(q,true)}${!Number.isInteger(q.answer)||q.type!=='mcq'?`<details><summary>مرجع التقويم</summary><p>${e(q.referenceAnswer)}</p></details><div class="notice">اعتماد المعلمة مطلوب؛ لا يوجد مفتاح اختيار آلي موثق لهذا البند.</div><div class="row">${act('race-review','إجابة مستوفية · ١٠ نقاط','btn light',`data-score="10" ${g.answered?'disabled':''}`)}${act('race-review','تحتاج متابعة','btn ghost',`data-score="0" ${g.answered?'disabled':''}`)}</div>`:''}${g.answered&&!g.done?`<div style="margin-top:20px">${act('race-next','التحدي التالي '+icon('arrow'),'btn light')}</div>`:''}`;

 }
 return heading('إتقان | PLAY',titles[g.type],'تدريب جماعي على شاشة المعلمة. لا يُحتسب إتقانًا فرديًّا.',act('board',icon('fullscreen')+' وضع السبورة','btn secondary'))+`<section class="game-stage"><div class="row">${icon(g.done?'check':'play')}<h2>${g.done?'أكملتم التحدي!':titles[g.type]}</h2></div>${html}${g.notice?`<div class="notice ${g.done?'success':''}" role="status">${e(g.notice)}</div>`:''}<div class="row" style="margin-top:23px">${act('finish-game',g.done?'حفظ الجلسة والعودة':'اختتام الجلسة','btn light')}${act('start-game','ابدئي من جديد','btn ghost',`data-id="${g.type}"`)}</div></section>`;
 }
 function quizReset(){V.selection=null;V.retry=false;V.hinted=false;}
 function about(){dialog('نطاق النسخة الحالية',`<div class="notice success">ست وحدات كاملة في الخريطة، وجميع صفحات الكتاب الأصلية وأنشطتها، مع مدخل «من أخلاق المؤمنين».</div><h3>ما يعمل محليًّا</h3><p>تصفح الدروس، والبحث في الأسئلة، وعرض صفحاتها، وتعيين المهمة، وإجابة الطالبة، والمراجعة البشرية، وحفظ المحاولة، ومعاينة التقرير. مساعد 45 يعرض أسئلة الدرس المختار، وسباق PLAY يستعملها.</p><h3>ما لا ندّعي اكتماله</h3><p>مفاتيح الحل ليست كاملة. التسجيلات الصوتية والفيديو غير مرفقة. رفوف تضم ثلاث قصص. لا دخول آمن أو مزامنة بين الأجهزة أو إرسال تلقائي أو توليد حي بالذكاء الاصطناعي.</p><div class="notice">هذه نسخة محتوى وتجربة، ببيانات افتراضية فقط. لا تُدخلي بيانات حقيقية ولا تنشريها بوصفها نظام تقارير محميًّا.</div>${act('close','العودة','btn full-width')}`); }
 function audit(){const a=D.contentAudit;dialog('سجل المحتوى والمطابقة',`<div class="notice success">المصدر المعتمد: الكتاب الذي يبدأ بقصة «المستقبل». استُبعد «الكتاب محلول.pdf» المختلف.</div><div class="stat-grid"><div class="stat-box"><b>${n(a.bookCards)}</b><small>بطاقات أنشطة من الكتاب</small></div><div class="stat-box"><b>${n(a.allComponents)}</b><small>مكوّنًا، بما فيه مدخل الكتاب</small></div><div class="stat-box"><b>${n(a.sourcePages)}</b><small>صفحة أصلية متاحة</small></div></div><p class="small">${e(a.countDefinition)}</p><h3>التصحيح</h3><p>${n(a.autoGradedBookCards)} بطاقة لها مفتاح آلي مدخل. ${n(a.manualBookCards)} بطاقة تراجعها المعلمة. ${n(a.observationCards)} نشاط أداء أو ملاحظة. ${n(a.cardsWithAnswerPage)} بطاقة مرتبطة بصفحة من ملف الإجابات الموافق، لكن بعض تلك الصفحات تحتوي بنودًا غير محلولة.</p><div class="notice">ملف الحل الموافق من ٤٥ صفحة وينتهي في أنشطة من الوحدة الثالثة؛ لا يُستخدم بوصفه حلًّا كاملًا للوحدات الست. بقية الإجابات لا تُخمن ولا تُحتسب خطأً آليًّا.</div><p>${e(a.transcription)}</p><p>التدريبات الموازية الثلاثة والأداء المستقل الثلاثة من إعداد إتقان، منفصلة عن بطاقات الكتاب. القصص الأصلية الثلاثة محفوظة في رفوف.</p><div class="row">${act('source-page','فهرس الكتاب','btn secondary',`data-page="6"`)}${act('registry','تنزيل سجل المحتوى','btn secondary')}</div>`); }
 function render(){
  const r=route();let content='';
  try{
   if(r.role==='teacher'){content=r.page==='home'?teacherHome():r.page==='curriculum'?curriculum(r):r.page==='lesson'?lesson(r):r.page==='class'?classPage():r.page==='play'?play():r.page==='game'?game(r):r.page==='library'?library(r):r.page==='story'?story(r):r.page==='review'?reviewPage():r.page==='reports'?reports():teacherHome();}
   else if(r.role==='student'){content=r.page==='home'?studentHome():r.page==='curriculum'?curriculum(r):r.page==='lesson'?lesson(r):r.page==='library'?library(r):r.page==='story'?story(r):r.page==='task'?quiz(r):r.page==='progress'?progress():studentHome();}
   else content=family();shell(content,r);
  }catch(err){console.error(err);shell(empty('تعذر عرض هذا القسم','لم نحذف بياناتك. يمكنك العودة إلى البداية وتنزيل بيانات التجربة.',link('teacher/home','العودة للبداية')),r);}
 }
 document.addEventListener('click',ev=>{
  const b=ev.target.closest('[data-do]');if(!b||b.disabled)return;ev.preventDefault();const k=b.dataset.do,id=b.dataset.id,ix=Number(b.dataset.index);
  try{
   if(k==='role'){document.body.classList.remove('board-mode');go(b.dataset.role+'/home');}
   else if(k==='context'){V.context=id;render();}
   else if(k==='unit'){V.unit=id;render();}
   else if(k==='tab'){V.tab=id;V.selected=[];render();}
   else if(k==='filter'){V.query=document.getElementById('qSearch').value;V.skill=document.getElementById('qSkill').value;render();}
   else if(k==='about')about();else if(k==='audit')audit();else if(k==='close')modal.close();
   else if(k==='read-book')dialog(currentLesson().title,bookMarkup());
   else if(k==='source-page')sourceViewer('book',b.dataset.page);
   else if(k==='answer-page'){if(route().role==='teacher')sourceViewer('answers',b.dataset.page);}
   else if(k==='source-next'||k==='source-prev'){if(currentSource)sourceViewer(currentSource.kind,currentSource.page+(k==='source-next'?1:-1));}
   else if(k==='registry'){const blob=new Blob([JSON.stringify({audit:D.contentAudit,units:D.units,questions:D.questions.map(q=>({id:q.id,lesson:q.lessonTitle,page:q.page,number:q.number,prompt:q.prompt,origin:q.origin,type:q.type,answerStatus:q.answerStatus,answerSourcePage:q.answerSourcePage}))},null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='itqan-curriculum-registry.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
   else if(k==='select-first'){V.selected=taskIds(currentLesson().id,V.tab);render();}
   else if(k==='class-prev'||k==='class-next'){V.classIndex=Math.max(0,V.classIndex+(k==='class-next'?1:-1));render();}
   else if(k==='font-plus'||k==='font-minus'){V.font=Math.max(15,Math.min(25,V.font+(k==='font-plus'?1:-1)));document.querySelectorAll('.story-text').forEach(el=>el.style.setProperty('--reading-font',V.font+'px'));}
   else if(k==='assign-default')assignDialog(taskIds(currentLesson().id));
   else if(k==='assign-independent')assignDialog(taskIds(currentLesson().id,'independent'),'independent');
   else if(k==='assign-selected')assignDialog(V.selected,V.tab==='independent'?'independent':'training');
   else if(k==='assign-story'){const s=D.stories.find(x=>x.id===id);assignDialog(s.questions.map(q=>q.id),'story',s.id);}
   else if(k==='student-demo'||k==='self-practice'){

    const meta=currentLesson();if(k==='self-practice'&&(meta.requiresAudio||meta.requiresVideo))return notify('هذا النشاط يحتاج إلى المسموع أو الفيديو الأصلي الذي توفره المعلمة؛ لا تبدئي الأسئلة قبل الاطلاع عليه.');
    const independent=k==='self-practice'&&V.tab==='independent',ids=k==='student-demo'?D.defaultTaskIds:taskIds(meta.id,V.tab);
    if(!ids.length)return notify('هذا الدرس نشاط أداء أو ملاحظة. نفّذيه مع المعلمة وفق صفحة الكتاب.');
    const signature=ids.join('|');let a=S.assignments.find(x=>x.studentIds.includes(V.learner)&&x.questionIds.join('|')===signature);
    if(!a){const aid=uid('task');S=C.assign(S,D,{id:aid,title:(k==='student-demo'?'المستقبل':meta.title)+(independent?' · أداء مستقل':' · مهمة من كتابي'),questionIds:ids,studentIds:[V.learner],kind:independent?'independent':'training'});save();a=S.assignments.find(x=>x.id===aid);}V.quizId=null;quizReset();go('student/task/'+a.id);
   }else if(k==='story-challenge'){const st=D.stories.find(x=>x.id===id);let a=S.assignments.find(x=>x.storyId===id&&x.studentIds.includes(V.learner));if(!a){const aid=uid('story');S=C.assign(S,D,{id:aid,title:'رفوف · '+st.title,questionIds:st.questions.map(q=>q.id),studentIds:[V.learner],kind:'story',storyId:st.id});save();a=S.assignments.find(x=>x.id===aid);}go('student/task/'+a.id);}
   else if(k==='choose'){V.selection=ix;document.querySelectorAll('.choice').forEach((el,i)=>{el.classList.toggle('selected',i===ix);el.setAttribute('aria-pressed',String(i===ix));});}
   else if(k==='hint'){V.hinted=true;render();}
   else if(k==='retry'){V.retry=true;V.selection=null;V.hinted=true;render();}
   else if(k==='next-question'){V.qi++;quizReset();render();document.getElementById('main').focus({preventScroll:true});}
   else if(k==='jump-question'){V.qi=ix;quizReset();render();}
   else if(k==='grade'){S=C.review(S,id,Number(b.dataset.score),document.getElementById('comment-'+id).value);save();notify('حُفظت المراجعة، وتحدثت بيانات التجربة.');render();}
   else if(k==='view-report'){V.reportStudent=id;render();}
   else if(k==='publish-reports'){S=C.publish(S,D);save();notify('اعتُمدت التقارير التي اكتملت مراجعتها. لم تُرسل إلى أي جهة.');render();}
   else if(k==='print')window.print();
   else if(k==='export'){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),demo:true,data:S},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='itqan-demo-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
   else if(k==='board'){document.body.classList.toggle('board-mode');if(document.body.classList.contains('board-mode'))document.documentElement.requestFullscreen?.().catch(()=>{});else if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});render();}
   else if(k==='toggle-timer'){V.running=!V.running;V.timerAt=Date.now();render();}
   else if(k==='reset-timer'){V.running=false;V.time=0;render();}
   else if(k==='observe'){V.observation[id]=b.dataset.value;render();}
   else if(k==='start-game')initGame(id);
   else if(k==='match-left'||k==='match-right'){const g=V.game;if(k==='match-left')g.left=ix;else g.right=ix;if(g.left!==null&&g.right!==null){if(g.left===g.right){if(!g.matched.includes(g.left)){g.matched.push(g.left);g.points+=10;}g.notice='رابط صحيح. أحسنتم!';}else g.notice='راجِعوا المعنى، ثم اختاروا رابطًا جديدًا.';g.left=null;g.right=null;}g.done=g.matched.length===3;if(g.done)g.notice='اكتمل جسر المفردات بثلاثة روابط صحيحة.';render();}
   else if(k==='order-up'||k==='order-down'){const ar=V.game.order,j=ix+(k==='order-up'?-1:1);if(j>=0&&j<ar.length)[ar[ix],ar[j]]=[ar[j],ar[ix]];V.game.notice='';render();}
   else if(k==='check-order'){const g=V.game;g.done=g.order.every((v,i)=>v===i);g.notice=g.done?'أحسنتم. أصبحت أحداث القصة مترابطة.':'ابحثوا عن بداية الحوار، ثم ما حدث بعد أسابيع، ثم النهاية.';if(g.done)g.points=30;render();}
   else if(k==='team'){V.game.team=ix;render();}

   else if(k==='race-answer'){
    const g=V.game;if(g.answered)return;const q=qby(g.questionIds[g.qi]);g.selected=ix;
    if(!Number.isInteger(q.answer)){g.notice='سُجّل اختيار المجموعة. تعتمده المعلمة وفق المصدر قبل إضافة نقاط اللعب.';render();return;}
    g.answered=true;if(ix===q.answer){g.teams[g.team]+=10;g.points+=10;g.notice='إجابة صحيحة. تقدم الفريق عشر نقاط.';}else g.notice='الإجابة تحتاج مراجعة. '+q.referenceAnswer;if(g.qi===g.questionIds.length-1){g.done=true;g.notice+=' اكتملت الجولة.';}render();
   }
   else if(k==='race-review'){const g=V.game;if(g.answered)return;const points=Number(b.dataset.score)===10?10:0;g.answered=true;g.points+=points;g.teams[g.team]+=points;g.notice=points?'اعتمدت المعلمة الإجابة. أضيفت عشر نقاط للمجموعة.':'تحتاج الإجابة إلى متابعة وفق المطلوب في السؤال.';if(g.qi===g.questionIds.length-1){g.done=true;g.notice+=' اكتملت الجولة.';}render();}
   else if(k==='race-next'){const g=V.game;g.qi++;g.answered=false;g.selected=null;g.notice='';g.team=1-g.team;render();}
   else if(k==='finish-game'){const g=V.game;if(g&&!g.logged){S.games.push({id:g.id,title:{match:'جسر المفردات',order:'خيط الحكاية',race:'سباق الصف'}[g.type],points:g.points,completed:g.done,at:new Date().toISOString()});g.logged=true;save();}document.body.classList.remove('board-mode');go('teacher/play');}
  }catch(err){notify(err.message||'تعذر إتمام العملية. حاولي مرة أخرى.');console.error(err);}
 });
 document.addEventListener('change',ev=>{
  const el=ev.target;
  if(el.dataset.pick){if(el.checked&&!V.selected.includes(el.dataset.pick))V.selected.push(el.dataset.pick);else if(!el.checked)V.selected=V.selected.filter(x=>x!==el.dataset.pick);const b=document.querySelector('[data-do="assign-selected"]');if(b)b.innerHTML=icon('send')+' تعيين المحدد ('+n(V.selected.length)+')';}
  if(el.id==='activeLesson'){V.activeLesson=el.value;V.classIndex=0;V.time=0;V.running=false;S.selectedLesson=el.value;save();if(route().page==='class')go('teacher/class/'+el.value);else render();}
   if(el.id==='sourcePageSelect'&&currentSource)sourceViewer(currentSource.kind,el.value);
   if(el.id==='learnerSelect'){V.learner=el.value;V.quizId=null;quizReset();render();}
  if(el.id==='familySelect'){V.reportStudent=el.value;render();}
 });
 document.addEventListener('input',ev=>{const el=ev.target;if(el.id==='lessonNote'){S.notes=el.value;save();}if(el.id==='answerText'){const f=el.closest('form'),key=`${V.learner}|${f.dataset.aid}|${f.dataset.qid}`;S.drafts[key]=el.value;save();}});
 document.addEventListener('submit',ev=>{
  const f=ev.target;if(!['assignForm','answerForm'].includes(f.id))return;if(f.id==='assignForm'&&!modal.open)return;ev.preventDefault();
  try{
   if(f.id==='assignForm'){const ids=JSON.parse(document.getElementById('assignIds').value),ss=[...f.querySelectorAll('[name="target"]:checked')].map(x=>x.value),kind=document.getElementById('assignKind').value;S=C.assign(S,D,{id:uid('task'),title:document.getElementById('assignTitle').value,questionIds:ids,studentIds:ss,kind,storyId:document.getElementById('assignStory').value||null});save();modal.close();notify('عُيّنت المهمة للحسابات المحددة. افتحي دور الطالبة لتجربتها.');render();}
   else{const q=qby(f.dataset.qid),value=q.type==='mcq'?V.selection:document.getElementById('answerText').value;S=C.submit(S,D,{id:uid('response'),studentId:V.learner,assignmentId:f.dataset.aid,questionId:q.id,value,usedHint:V.hinted});save();V.retry=false;render();}
  }catch(err){const el=document.getElementById(f.id==='assignForm'?'assignError':'answerError');if(el)el.textContent=err.message;else notify(err.message);}
 });
 window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
 window.addEventListener('storage',ev=>{if(ev.key===KEY&&ev.newValue){try{const s=JSON.parse(ev.newValue);if(s.schema===1){S=s;if(!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))render();}}catch{}}});
 window.addEventListener('keydown',ev=>{if(ev.key==='Escape'){document.body.classList.remove('board-mode');}});
 setInterval(()=>{if(V.running){const dt=Math.floor((Date.now()-V.timerAt)/1000);if(dt){const previousTime=V.time;V.time=Math.min(2700,V.time+dt);V.timerAt+=dt*1000;if(route().page==='class'&&[180,780,1500,2220,2520].some(t=>previousTime<t&&V.time>=t))render();const el=document.getElementById('classTimer');if(el)el.textContent=timeText(2700-V.time);if(V.time>=2700){V.running=false;notify('انتهت مدة الحصة المقترحة.');render();}}}},250);
 if(!location.hash)history.replaceState(null,'','#teacher/home');render();
})();
